[build]
  publish = "web"

[functions]
  directory = "netlify/functions"

[functions."test_run"]
  included_files = ["app/**"]

# Optional: security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
